experimentName: Indiv_Student
trialConcurrency: 1
maxExperimentDuration: 48h
maxTrialNumber: 1

searchSpaceFile: search_space.json
useAnnotation: false
trialCommand: python3 train.py --epochs 160 --student resnet8 --cuda 1 --dataset cifar10
  --description indiv
trialCodeDirectory: .
trialGpuNumber: 1
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True